name: Python Test Automation

on:
  push:
    branches:
      - master  # veya main, kullanmakta olduğunuz dal adı
  pull_request:
    branches:
      - master  # veya main, kullanmakta olduğunuz dal adı

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Python sürümünü burada belirtiyoruz

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Bu, requirements.txt'teki tüm bağımlılıkları yükler
          pip install pytest  # pytest'i ayrıca yükle

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q  # Testlerinizi burada çalıştırıyoruz
