name: Python Test Automation

on:
  push:
    branches:
      - main  # main dalına yapılan push işlemleri ile tetiklenecek
  pull_request:
    branches:
      - main  # main dalına yapılan pull request'ler ile tetiklenecek

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub Actions'ın çalışacağı işletim sistemi (Ubuntu)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # GitHub'dan projeyi çekiyoruz

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Python sürümünü ayarlıyoruz (örneğin, 3.10)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pip'i güncelliyoruz
          pip install -r requirements.txt  # Gereksinim dosyasındaki bağımlılıkları yüklüyoruz

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Testleri çalıştırıyoruz, hata durumunda 1 test sonrasında duruyor
